name: Build & Publish

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

permissions:
  contents: read

env:
  CI: true

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'chore') && contains(github.event.pull_request.title, 'release') }}
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set Permissions
        run: chmod +x ./gradlew

      - name: Build & Maven Publish
        run: ./gradlew publish --stacktrace
        env:
          urkaz_maven_pass: ${{ secrets.URKAZ_MAVEN_PASS }}
