name: Create Release PR

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'fabric/**'
      - 'forge/**'
      - 'neoforge/**'
      - '**.gradle'
      - '**.properties'

permissions:
  contents: write
  pull-requests: write

env:
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple